name: Docker Image CI
on:
  push:
    branches: [ "main" , "Alg1-4-Dockerization"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  test_django:
    uses: SENG-499-Company2-B01/Algs1/.github/workflows/django.yml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_django]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alg1:$(date +%s)